server:
  port: 8080

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nextu?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true # true 로 설정 시 JPA 쿼리 출력
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 내가 엔티티에 설정한 column 명 따라감
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    port: 6379 # 레디스 서버 포트
    host: localhost
    password: abcde

jwt:
  header: Authorization # 데이터 통신 시 헤더 패킷의 이름
  accessTokenExpiresIn: 3600 # 토큰 만료 시간 - 1 hour
  refreshTokenExpiresIn: 86400 # 토큰 만료 시간 - 24 hours
